config/routes.rb
Meck::Application.routes.draw do
  get "upload/index"

  get "upload/new"
  resources :uploads

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root to: 'pages#home'
  
  match '/new_upload', to: 'upload#new'

  match '/contact', to: 'pages#contact'

  match '/help',    to: 'pages#help'

  match '/about',   to: 'pages#about'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :product
end

app/models/upload.rb
class Upload < ActiveRecord::Base
  attr_accessible :file_name, :file_size
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact
  end

  def help
  end

  def about
  end
end

app/controllers/upload_controller.rb
class UploadController < ApplicationController
  def index
    @uploads= Upload.all
     respond_to do |format|
       format.html
       format.xml {render :xml=> @uploads}
     end
  end
  def show
    @upload = Upload.find(params[:id])
    respond_to do |format|
      format.html
      format.xml {render :xml=> @uploads}
    end
  end

  def new
    @upload= Upload.new
    respond_to do |format|
      format.html
      format.xml {render :xml=> @uploads}
    end
  end
  def create
    @upload= Upload.new(params[:upload])
    respond_to do |format|
      if @upload.save
        format.html {redirect_to(@upload, :notice => "upload successful")}
        format.xml {render :xml => @upload, :status => :created, :location => @upload}
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @upload.errors, :status => :unprocessable_entity }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/views/layouts/_footer.html.erb
 
	<footer class="grid-wrap">
		<ul class="grid col-one-third social">
			<li><%=link_to "RSS", '#'%></li>
			<li><%=link_to "Facebook", '#'%></li>
			<li><%=link_to "Twitter", '#'%></li>
			<li><%=link_to "Google+", '#'%></li>
			<li><%=link_to "Flicker", '#'%></li>
		</ul>
	
		<div class="up grid col-one-third ">
			<a href="#navtop" title="Go back up">&uarr;</a>
		</div>
		
		<nav class="grid col-one-third ">
			<ul>
				<li><a href="index.html">Home</a></li>
				<li><a href="about.html">About</a></li>
				<li><a href="works.html">Works</a></li>
				<li><a href="services.html">Services</a></li>
				<li><a href="blog.html">Blog</a></li>
				<li><a href="contact.html">Contact</a></li>
			</ul>
		</nav>
	</footer>

app/views/layouts/_header.html.erb
 <header id="navtop">
    
		<%=link_to image_tag("logo.png",alt: "meck",), root_path %>
                
		<nav class="fright">
			<ul>
				<li class="navactive"><%=link_to "Home", root_path %></li>
				<li><%=link_to "About", about_path %></li>
			</ul>
			<ul>
				<li><%= link_to "Products", '#'%></li>
				<li><%= link_to "Services", '#' %></li>
			</ul>
			<ul>
				<li><%= link_to "Blog", '#'%></li>
				<li><%= link_to "Contact", contact_path %></li>
			</ul>
		</nav>
    
	</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Meck</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim'%>
</head>
<body>
  <div class="container">
 <%= render 'layouts/header'%>
  </div>
  <div class="container">
           
           <%= yield %>
  </div>
  <div class="divide-top">
 <%= render 'layouts/footer'%>
  </div>
</body>
</html>

app/views/pages/about.html.erb
<div class="about-page main grid-wrap">

		<header class="grid col-full">
		<hr>
			<p class="fleft">About</p>
		</header>

		
		
		<aside class="grid col-one-quarter mq2-col-full">
			<p class="mbottom">.
			</p>
			<menu>
				<ul>
					<li><%=link_to "Our team", '#navteam', class:"arrow"%></li>
					<li><%= link_to "Our philosopy", '#navphilo', class:"arrow"%></li>
					<li><%=link_to "Our place", '#navplace', class:"arrow"%></li>
					<li><%=link_to "Our products", '#navothers', class:"arrow"%></li>
				</ul>
			</menu>
		</aside>
		
		<section class="grid col-three-quarters mq2-col-full">
			<%= image_tag "team.jpg", alt:"" %>
			
			<article id="navteam">
			<h2>Our team</h2>
			<p>Lng .</p>
			<p>Lor.</p>
			</article>
			
			<article id="navphilo">
			<h2>Our philosophy</h2>
			<p>. Su</p>
			<p>Lo.</p>
			</article>
			
			<article id="navplace">
			<h2>Our place</h2>
			<p>L</p>
			<p>Lo.</p>
			</article>
					
			<article id="navother">
			<h2>Our location</h2>
			<p>Lt.</p>
			<p>Lhit.</p>
			</article>
		
		</section>
		
	</div>

app/views/pages/contact.html.erb
<div class="contact-page main grid-wrap">

		<header class="grid col-full">
			<hr>
			<p class="fleft">Contact</p>
		</header>

		
		
		<aside class="grid col-one-quarter mq2-col-one-third mq3-col-full">

			<p class="mbottom">We would love to talk to you and answer all of your questions</p>
			
			<address class="mbottom">
				<h5>DESIGNA studio </h5>
				3615 Fake Street <br >
				Level 5, Door 123 <br >
				1010 WHATEVER<br >
				<a href="http://maps.google.com">Get directions</a>
			</address>
		
			<p class="mbottom">
				00 77 66 55 33<br >
				00 77 66 55 33</p>
			<p class="mbottom">
				<a href="#">address@email.com</a><br >
				<a href="#">Designa Studio on Facebook</a><br >
				<a href="#">@designstudio on Twitter</a><br >
				<a href="#">Designa Studio on Google+</a>
			</p>
			<p>
				<h6>Openning hours: </h6>
				Monday to Friday <br >
				09h00 to 17h00
			</p>
		
		</aside>
		
		<section class="grid col-three-quarters mq2-col-two-thirds mq3-col-full">
			<h2>Drop us a message</h2>
			<p class="warning">Don't forget to put your own email address in the in the msg!</p>
			
			<form id="contact_form" class="contact_form" action="contact.php" method="post" name="contact_form">	
				<ul>
					<li>
						<label for="name">Your name:</label>
						<input type="text" name="name" id="name" required class="required" >
					</li>
					<li>
						<label for="email">Email:</label>
						<input type="email" name="email" id="email" required placeholder="JohnDoe@gmail.com" class="required email">
					</li>	
					<li>
						<label for="message">Message:</label>
						<textarea name="message" id="message" cols="100" rows="6" required  class="required" ></textarea>
					</li>
					<li>
						<button type="submit" id="submit" name="submit" class=" button fright">Send it</button>
					</li>	
				</ul>			
			</form>
		</section>
                </div>
                

app/views/pages/help.html.erb
<h1>Pages#help</h1>
<p>Find me in app/views/pages/help.html.erb</p>

app/views/pages/home.html.erb
<div class="home-page main">
	<section class="grid-wrap" >
		<header class="grid col-full">
			<hr>
			<p class="fleft">Home</p>
                        <p class="arrow fright"><%=link_to "see more infos",'#' %></p>
			
		</header>
		
		<div class="grid col-one-half mq2-col-full">
			<h1>Desktop   apps<br>
			Iphone   Apps <br>
			Android   Apps</h1>
			<p>Mecksolution is web/desktop development company located in India.We have large task force of developer dedicated to tailormade apps and off the shelf apps
			</p>
			<p>Also we offer other services like support application deployment
			</p>
		</div>
			
	
		 <div class="slider grid col-one-half mq2-col-full">
		   <div class="flexslider">
		     <div class="slides">
		       <div class="slide">
		           	<figure>
                                  <%= image_tag "img2.jpg", alt:""%>
		                
		                 <figcaption>
		                 	<div>
		                 	<h5>Caption 1</h5>
		                 	<p>meck centre <%=link_to "link text", '#'%></link_to></p>
		                 	</div>
		                 </figcaption>
		             	</figure>
		           </div>
		           
		           <div class="slide">
		               	<figure>
                                  <%= image_tag "img.jpg", alt: ""%>
		                     
		                     <figcaption>
		                     	<div>
		                     	<h5>Caption 2</h5>
		                     	<p>meck centre 2</p>
		                     	</div>
		                     </figcaption>
		                 	</figure>
		               </div>
		            </div>
		   </div>
		 </div>
		
		 </section>
</div>

app/views/upload/_form.html.erb
<%= form_for(@upload, :html => { :multipart => true }) do |upload_form| %>
  <% if @upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@upload.errors.count, "error") %> prohibited this upload from being saved:</h2>

      <ul>
      <% @upload.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= upload_form.label :upload %><br />
    <%= upload_form.file_field :attach %>
  </div>
  
  
  <div class="actions">
    <%= upload_form.submit %>
  </div>
<% end %>

app/views/upload/index.html.erb
<h1>Listing File Uploads</h1>

<table>
  <tr>
    <th>File</th>
   
    <th></th>
  </tr>

<% @uploads.each do |upload| %>
  <tr>
    <td><%= upload.attach.url %></td>
   
    <td><%= link_to 'Download', upload %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Upload', new_upload_path %>

app/views/upload/new.html.erb
<h1>New upload</h1>
<%= render 'upload/form' %>

<%= link_to 'back', uploads_path %>

app/views/upload/show.html.erb
<p class="notice"><%= notice %></p>

<p>
  <b>File url:</b>
  <%= link_to "#{@upload.attach.url}", :action => 'verify', :id => @upload.id %>
</p>





<%= link_to 'Back', uploads_path %>